owners = []
nickname = "hazeman"
alt_nicks = ["hazeman_", "hazeman__"]
username = "hazeman"
realname = "hazeman"
server = "127.0.0.1"
port = 6667
use_ssl = false
encoding = "UTF-8"
channels = ["#test"]
umodes = "+RB-x"
user_info = "hi im hazeman"
version = "irc:git:Rust"
source = "https://github.com/aatxe/irc"
ping_time = 180
ping_timeout = 10
burst_window_length = 8
max_messages_in_burst = 15

[channel_keys]

[options]
